name: ParentsListMaker
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "SECRET_KEY=${{ secrets.AES_KEY }}" >> .env
          echo "AES_KEY=${{ secrets.API_KEY }}" >> .env
          echo "DOMAIN_EMAIL=${{ secrets.DOMAIN_EMAIL }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
          echo "PRODUCTION=${{ secrets.PRODUCTION }}" >> .env
          echo "BACKEND_HOST=${{ secrets.BACKEND_HOST }}" >> .env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
      - name: Run tests
        run: |
          pytest
